"""
            config = Config()
            directory = f"{config.location}"
            volume_yaml = path_expand(f"{directory}/volume.yaml")


            try:
                with open(volume_yaml) as file:
                    dic = yaml.load(file, Loader=yaml.FullLoader)
                counter = dic["counter"]
                print(counter)
                user = dic["user"]
                created_name = f"{user}-{cloud}-{counter}"
                print(created_name)
                dic["counter"] += 1
                with open(volume_yaml, 'w') as file:
                    documents = yaml.dump(dic, file)
            except:
                Console.error("the volume.yaml file does not exist."
                              "You need to implement "
                              "the case so it gets autogenerated")
                raise NotImplementedError

            return created_name
"""



{'Reservations':
     [{'Groups': [],
       'Instances':
         [{'AmiLaunchIndex': 0,
           'ImageId': 'ami-0fc20dd1da406780b',
           'InstanceId': 'i-0bb07f16da9b76ac9',
           'InstanceType': 't2.micro',
           'KeyName': 'aws_ec2_cert',
           'LaunchTime': datetime.datetime(2020, 4, 2, 23, 4, 38, tzinfo=tzutc()),
           'Monitoring': {'State': 'disabled'},
           'Placement': {'AvailabilityZone': 'us-east-2a', 'GroupName': '', 'Tenancy': 'default'},
           'PrivateDnsName': 'ip-172-31-11-151.us-east-2.compute.internal',
           'PrivateIpAddress': '172.31.11.151',
           'ProductCodes': [],
           'PublicDnsName': 'ec2-18-188-139-24.us-east-2.compute.amazonaws.com',
           'PublicIpAddress': '18.188.139.24',
           'State': {'Code': 16, 'Name': 'running'},
           'StateTransitionReason': '',
           'SubnetId': 'subnet-bd46b6d6',
           'VpcId': 'vpc-e334fc88',
           'Architecture': 'x86_64',
           'BlockDeviceMappings':
               [{'DeviceName': '/dev/sda1',
                 'Ebs':
                     {'AttachTime': datetime.datetime(2020, 4, 2, 23, 4, 39, tzinfo=tzutc()),
                      'DeleteOnTermination': True,
                      'Status': 'attached',
                      'VolumeId': 'vol-02479a5b814ca5edb'
                      }
                 },
                {'DeviceName': '/dev/sdb',
                 'Ebs': {'AttachTime': datetime.datetime(2020, 4, 2, 23, 49, 3, tzinfo=tzutc()),
                         'DeleteOnTermination': False,
                         'Status': 'attached',
                         'VolumeId': 'vol-05c7c6f5fe0f8a7d3'}
                 },
                {'DeviceName': '/dev/sdd',
                 'Ebs': {'AttachTime': datetime.datetime(2020, 4, 2, 23, 49, 4, tzinfo=tzutc()),
                         'DeleteOnTermination': False,
                         'Status': 'attached',
                         'VolumeId': 'vol-0cb1f13efa9466621'}
                 }
                ],
           'ClientToken': '',
           'EbsOptimized': False,
           'EnaSupport': True,
           'Hypervisor': 'xen',
           'NetworkInterfaces':
               [
                   {'Association':
                        {'IpOwnerId': 'amazon',
                         'PublicDnsName': 'ec2-18-188-139-24.us-east-2.compute.amazonaws.com',
                         'PublicIp': '18.188.139.24'
                         },
                    'Attachment':
                        {'AttachTime': datetime.datetime(2020, 4, 2, 23, 4, 38, tzinfo=tzutc()),
                         'AttachmentId': 'eni-attach-075db3070e4e72af9',
                         'DeleteOnTermination': True,
                         'DeviceIndex': 0,
                         'Status': 'attached'
                         },
                    'Description': 'Primary network interface',
                    'Groups':
                        [
                            {'GroupName': 'launch-wizard-8',
                             'GroupId': 'sg-0cc4a0fc10b0c8bd1'}
                        ],
                    'Ipv6Addresses': [],
                    'MacAddress': '02:ed:e6:8a:7d:0e',
                    'NetworkInterfaceId': 'eni-066597e73258cf205',
                    'OwnerId': '998726019676',
                    'PrivateDnsName': 'ip-172-31-11-151.us-east-2.compute.internal',
                    'PrivateIpAddress': '172.31.11.151',
                    'PrivateIpAddresses':
                        [
                            {'Association':
                                 {'IpOwnerId': 'amazon',
                                  'PublicDnsName': 'ec2-18-188-139-24.us-east-2.compute.amazonaws.com',
                                  'PublicIp': '18.188.139.24'
                                  },
                             'Primary': True,
                             'PrivateDnsName': 'ip-172-31-11-151.us-east-2.compute.internal',
                             'PrivateIpAddress': '172.31.11.151'
                             }
                        ],
                    'SourceDestCheck': True,
                    'Status': 'in-use',
                    'SubnetId': 'subnet-bd46b6d6',
                    'VpcId': 'vpc-e334fc88',
                    'InterfaceType': 'interface'
                    }
               ],
           'RootDeviceName': '/dev/sda1',
           'RootDeviceType': 'ebs',
           'SecurityGroups':
               [
                   {
                       'GroupName': 'launch-wizard-8',
                       'GroupId': 'sg-0cc4a0fc10b0c8bd1'
                   }
               ],
           'SourceDestCheck': True,
           'Tags': [
               {
                   'Key': 'Name',
                   'Value': 'xin-vm-3'
               }
           ],
           'VirtualizationType': 'hvm', 'CpuOptions': {'CoreCount': 1, 'ThreadsPerCore': 1}, 'CapacityReservationSpecification': {'CapacityReservationPreference': 'open'}, 'HibernationOptions': {'Configured': False}, 'MetadataOptions': {'State': 'applied', 'HttpTokens': 'optional', 'HttpPutResponseHopLimit': 1, 'HttpEndpoint': 'enabled'}}], 'OwnerId': '998726019676', 'ReservationId': 'r-0660b5bfb723fa4b3'}], 'ResponseMetadata': {'RequestId': '9ed82cbb-7f57-4ee8-a32a-fb7d4b7a1d02', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '9ed82cbb-7f57-4ee8-a32a-fb7d4b7a1d02', 'content-type': 'text/xml;charset=UTF-8', 'transfer-encoding': 'chunked', 'vary': 'accept-encoding', 'date': 'Fri, 03 Apr 2020 00:11:07 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}




{'Attachments':
     [
         {'AttachTime': datetime.datetime(2020, 4, 3, 13, 32, 6, tzinfo=tzutc()),
          'Device': '/dev/sda1',
          'InstanceId': 'i-005bfb2b0768aca4e',
          'State': 'attached',
          'VolumeId': 'vol-033b70613abaa859f',
          'DeleteOnTermination': True}],
    'AvailabilityZone': 'us-east-2a',
    'CreateTime': datetime.datetime(2020, 4, 3, 13, 32, 6, 299000, tzinfo=tzutc()),
    'Encrypted': False,
    'Size': 8,
    'SnapshotId': 'snap-085c8383cc8833286',
    'State': 'in-use',
    'VolumeId': 'vol-033b70613abaa859f',
    'Iops': 100,
    'VolumeType': 'gp2',
    'AttachedToVm': ['xin-vm-1']}
